basho/riak-nodejs-client

.gitignore
.travis.yml
Gruntfile.js
Makefile
README.md
build/common.mk
build/install-deps
buildbot/Makefile
lib/commands/commandbase.js
lib/commands/ping.js
lib/core/riakcluster.js
lib/core/riakconnection.js
lib/core/riaknode.js
package.json
test/debug-log.js
test/integration/riakconnection.js
test/integration/testparams.js
test/security/security.js

* Add `Makefile` to easily run grunt targets
* `make install-deps` is super handy on Ubuntu 12
* Buildbot related stuff

Ready: CLIENTS-288 Continuous Integration

---

.gitignore
README.md
RELNOTES.md
build/common.mk
build/publish
npm-shrinkwrap.json
package.json

Add a publish target. Just about done testing.

Ready: Big Red Button CLIENTS-304

---

lib/client.js
test/unit/client.js

Remove extra exports from client.js since they threw me off what was really exported.

Less code, less derp

---

lib/client.js
lib/core/riakconnection.js
lib/core/riaknode.js
test/integration/core/riaknode.js
test/integration/riakconnection.js

Healthcheck now plugable, defaults to a Ping. Integration tests included.
Also fixed variable name in Client.mapReduce()

RiakNode pluggable healthcheck

---

lib/core/defaultnodemanager.js
lib/core/nodemanager.js
lib/core/riakcluster.js
test/integration/core/riakcluster.js

Node selection now pluggable

---

CONTRIBUTING.md
README.md

Added contribution + cleaned up README. Still in need of a roadmap.

updated README

---

Gruntfile.js
README.md
lib/commands/crdt/updatemap.js

This makes it convenient to use strings when dealing with Register data types so you don't have to `new Buffer()` all the time.
Also, small improvement to detecting whether or not a value is a string.

Add String detection to setRegister()

---

CONTRIBUTING.md
README.md
RELNOTES.md

I've found some great language thanks to working on [the PHP client](https://github.com/basho/riak-php-client/pull/94) and want to bring it to node as well.

Phrasing, formatting and the such

---

lib/commands/crdt/updatemap.js
lib/core/riakcluster.js
lib/core/riakconnection.js
lib/core/riaknode.js
test/integration/core/riakcluster.js
test/integration/yokozuna/search.js
test/unit/crdt/updatemap.js
test/unit/riakconnection.js

ByteBuffer toBuffer() issue.

---

RELNOTES.md
lib/core/riakcluster.js
test/unit/riakcluster.js

Ensure that RiakCluster uses a new instance of DefaultNodeManager

---

.gitignore
Gruntfile.js
README.md
benchmarks/kv.js
lib/commands/kv/storevalue.js
lib/core/riakcluster.js
lib/core/riakconnection.js
lib/core/riaknode.js
npm-shrinkwrap.json
package.json
test/integration/kv/storevalue.js

Use cork and uncork when sending protobuf header and body.

---

lib/commands/kv/deletevalue.js
lib/commands/yokozuna/storeindex.js
test/unit/yokozuna/storeindex.js

Add the timeout field to RpbYokozunaIndexPutReq

READY: CLIENTS-402

---

lib/commands/kv/fetchpreflist.js
test/integration/kv/fetchpreflist.js
test/integration/kv/fetchvalue.js
test/integration/testparams.js
test/unit/fetchpreflist.js

CLIENTS-331

---

lib/commands/yokozuna/storeindex.js
test/integration/yokozuna/search.js
test/unit/yokozuna/storeindex.js

Fixes issue #60 (CLIENTS-410).

Add NVal to StoreIndex command

---

.gitignore
lib/commands/crdt/fetchcounter.js
lib/commands/crdt/fetchmap.js
lib/commands/crdt/fetchset.js
test/integration/crdt/updateandfetchcounter.js
test/integration/crdt/updateandfetchmap.js
test/integration/crdt/updateandfetchset.js

Fixes #65. Change "notFound" to "isNotFound" to be consistent with KV responses.

Resolve issue #65

---

lib/commands/kv/riakobject.js
test/integration/kv/storevalue.js
test/unit/storevalue.js

Add "Content Encoding" to RiakObject

---

lib/client.js
lib/commands/kv.js
lib/commands/kv/riakobject.js
test/unit/client.js
test/unit/core/riakcluster.js
test/unit/core/riakconnection.js
test/unit/core/riaknode.js
test/unit/kv/deletevalue.js
test/unit/kv/fetchbucketprops.js
test/unit/kv/fetchpreflist.js
test/unit/kv/fetchvalue.js
test/unit/kv/listbuckets.js
test/unit/kv/listkeys.js
test/unit/kv/riakobject.js
test/unit/kv/secondaryindexquery.js
test/unit/kv/storebucketprops.js
test/unit/kv/storevalue.js

Ensure that tombstones don't mess up JSON parsing.
Fix some issues with FetchPreflist command not being exported correctly.
Fixes #74.

CLIENTS-493

---

README.md
lib/commands/kv/fetchvalue.js
lib/core/riakcluster.js
test/unit/kv/fetchvalue.js

Minor changes to the code in PR #78 (CLIENTS-500)
Thanks @mogadanez

Catch exception when JSON.parse throws exception.

---

lib/commands/kv/secondaryindexquery.js
test/unit/kv/secondaryindexquery.js

Small improvements to PR#82
Fixes #80 
Thanks a lot @mogadanez

CLIENTS-502

---

README.md
lib/commands/crdt/fetchcounter.js
lib/commands/crdt/fetchmap.js
lib/commands/crdt/fetchset.js
lib/commands/crdt/updatecounter.js
lib/commands/crdt/updatemap.js
lib/commands/crdt/updateset.js
lib/commands/kv/deletevalue.js
lib/commands/kv/fetchpreflist.js
lib/commands/kv/fetchvalue.js
lib/commands/kv/storevalue.js
test/unit/commandbase.js
test/unit/kv/deletevalue.js
test/unit/kv/fetchpreflist.js
test/unit/kv/fetchvalue.js
test/unit/kv/storevalue.js

Allow binary riak keys

---

lib/client.js

Signed-off-by: GabrielNicolasAvellaneda <avellaneda.gabriel@gmail.com>

Corrected npm package name in documentation example.

---

classes/Client.html

Signed-off-by: GabrielNicolasAvellaneda <avellaneda.gabriel@gmail.com>

Corrected npm package name in example code.

---

lib/core/riakcluster.js

Signed-off-by: GabrielNicolasAvellaneda <avellaneda.gabriel@gmail.com>

Corrected method name in the Builder of RiakCluster.

---

README.md
lib/core/riakcluster.js
test/integration/core/riakcluster.js

Parameterize the queue submit interval of RiakCluster

---

Gruntfile.js
lib/commands/commandbase.js
lib/commands/kv/fetchbuckettypeprops.js
lib/commands/kv/fetchpropsbase.js
lib/commands/kv/storebuckettypeprops.js
lib/commands/kv/storepropsbase.js
test/integration/kv/fetchandsetbuckettypeprops.js
test/integration/testparams.js
test/unit/kv/fetchbuckettypeprops.js
test/unit/kv/storebuckettypeprops.js

READY: Implement Get/Set Bucket Type Properties

---

README.md
RELNOTES.md
lib/client.js
lib/commands/kv.js
test/unit/client.js

Add bucket type property operations to Client

---

lib/core/riakcluster.js
lib/core/riaknode.js
test/integration/core/riakcluster.js
test/integration/core/riaknode.js

Add callbacks to `.stop()` methods.

---

RELNOTES.md
lib/client.js
lib/core/riakcluster.js
test/integration/client.js

Ensure that `Riak.Client` parses its argument list correctly.

---

RELNOTES.md
index.js
lib/client.js
lib/commands/kv/fetchvalue.js
lib/core/riakcluster.js
lib/core/riakconnection.js
lib/core/riaknode.js
test/integration/client.js
test/integration/core/riakcluster.js
test/integration/core/riaknode.js
test/integration/ts/timeseries.js

Passes a useful object as the second argument to the callbacks.

Improve start / stop callbacks [JIRA: CLIENTS-691]

---

lib/client.js
lib/commands/ts.js
lib/commands/ts/describe.js
lib/commands/ts/query.js
test/integration/ts/timeseries.js
test/unit/client.js
test/unit/commandbase.js

* Add `DESCRIBE` tests
* Add method to encapsulate retrieving table description
* Add tests to ensure `CREATE TABLE` works correctly via query method

READY: RTS-666 / RTS-798

---

lib/client.js
lib/commands/kv.js
lib/commands/kv/resetbucketprops.js
lib/core/riakconnection.js
test/integration/core/riakcluster.js
test/integration/crdt/updateandfetchcounter.js
test/integration/crdt/updateandfetchmap.js
test/integration/crdt/updateandfetchset.js
test/integration/kv/fetchandsetbucketprops.js
test/integration/kv/fetchandsetbuckettypeprops.js
test/integration/kv/fetchpreflist.js
test/integration/kv/fetchvalue.js
test/integration/kv/listbuckets.js
test/integration/kv/listkeys.js
test/integration/kv/resetbucketprops.js
test/integration/kv/secondaryindexquery.js
test/integration/kv/storevalue.js
test/integration/mapreduce/mapreduce.js
test/integration/testparams.js
test/integration/ts/timeseries.js
test/integration/yokozuna/search.js
test/integration/yokozuna/storeandfetchschema.js
test/integration/yokozuna/storefetchdeleteindex.js
test/security/security.js
test/unit/client.js
test/unit/commandbase.js
test/unit/core/riakconnection.js

Resolves #142 (CLIENTS-783) (CLIENTS-793)

READY: "Reset Bucket Properties" command

---

RELNOTES.md
lib/core/authreq.js
lib/core/riakcluster.js
lib/core/riakconnection.js
lib/core/riaknode.js
lib/core/starttls.js
lib/core/utils.js
package.json
test/integration/core/riakcluster.js
test/integration/core/riakconnection.js
test/integration/core/riaknode.js
test/integration/crdt/updateandfetchcounter.js
test/integration/ts/timeseries.js
test/security/security.js
test/unit/core/riakconnection.js

Depends on #143 
Resolves #144 (CLIENTS-795) 
Test via stopping a Riak node via `SIGSTOP`

READY: Implement read/write timeouts

---

lib/core/riakcluster.js
lib/core/riaknode.js
lib/core/utils.js
test/integration/core/riaknode.js
test/unit/core/riaknode.js
test/unit/core/utils.js

Resolves #151 (CLIENTS-57) (CLIENTS-829)

READY: Add externalLoadBalancer option to RiakNode

---

test/integration/ts/timeseries.js

Modify TS tests for 1.3 support

---

lib/commands/ts/utils.js
lib/commands/yokozuna/search.js
lib/utils.js
test/unit/yokozuna/search.js

READY: fix conversion from YZ search results

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
RELNOTES.md
lib/commands/yokozuna/search.js
test/unit/yokozuna/search.js

READY: Riak Search document decoding / parsing bug

---

test/integration/ts/timeseries.js

Modify TS integration tests for Riak TS 1.4

---

.travis.yml
README.md
package.json
test/unit/core/riaknode.js

Update dependencies via npm-check-updates

---

lib/commands/ts/data.js
lib/commands/ts/store.js
lib/commands/ts/utils.js
test/integration/ts/timeseries.js
test/unit/ts/data.js
test/unit/ts/store.js

Please ensure the following is present in your Pull Request:
Pull Requests that are small and limited in scope are most welcome.
Thank you!

Add TS 1.5 Blob Type

---

lib/commands/commandbase.js
lib/commands/crdt.js
lib/commands/crdt/fetchset.js
lib/commands/crdt/updategset.js
lib/commands/crdt/updatesetbase.js
lib/commands/kv/fetchpropsbase.js
test/integration/crdt/updateandfetchgset.js
test/integration/testparams.js
test/unit/client.js
test/unit/crdt/fetchcounter.js
test/unit/crdt/fetchmap.js
test/unit/crdt/fetchset.js
test/unit/crdt/updatecounter.js
test/unit/crdt/updategset.js
test/unit/crdt/updatehll.js
test/utils.js

GSet support / RIAK-2907

---

lib/client.js
lib/commands/commandbase.js
lib/commands/kv/listbuckets.js
lib/commands/kv/listkeys.js
lib/commands/ts/listkeys.js
lib/commands/yokozuna/deleteindex.js
lib/errors.js
lib/utils.js
test/integration/kv/listbuckets.js
test/integration/kv/listkeys.js
test/integration/testparams.js
test/integration/ts/timeseries.js
test/unit/commandbase.js
test/unit/kv/listbuckets.js
test/unit/kv/listkeys.js
test/unit/ts/listkeys.js

Fixes #182 (CLIENTS-1066) (CLIENTS-1066) (CLIENTS-1066) and [CLIENTS-1066](https://bashoeng.atlassian.net/browse/CLIENTS-1066)

Implement exceptions for listing operations.
